spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/wequiz
    driver-class-name: org.postgresql.Driver
    username: wequizadmin
    password: 'wequizadmin'
