spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/wequiz
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: wequizadmin
    password: wequizadmin

social:
  client:
    kakao:
      redirect-uri: http://localhost:3000/sign-in/kakao/callback
    google:
      redirect-uri: http://localhost:3000/sign-in/google/callback
