server:
  port: 8080
  shutdown: graceful
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 500

springdoc:
  swagger-ui:
    path=/:

spring:
  config:
    import: 'aws-secretsmanager:wequiz/aws/back'
  servlet:
    #TODO: 파일 사이즈 상의 후 조정
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  profiles:
    active: local

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  region: 'ap-northeast-2'

jwt:
  secret: qwerasdfzxcvdsafdsaffdasafdfdsafdsafdsafdsasfda
  access-token-expiration: 86400000
  refresh-token-expiration: 2592000000

minio:
  access:
    key: ${MINIO_ACCESS_KEY}
    secret: ${MINIO_SECRET_KEY}
  bucket:
    pdf: ${MINIO_BUCKET_PDF}
    profileImage: ${MINIO_BUCKET_PROFILE_IMAGE}
  endpoint: ${MINIO_ENDPOINT}

url:
  ml: ${ML_URL}

social:
  client:
    kakao:
      client-id: ${KAKAO_API_KEY}
      client-secret: ${KAKAO_API_SECRET}
      grant_type: authorization_code
    google:
      client-id: ${GOOGLE_API_KEY}
      client-secret: ${GOOGLE_API_SECRET}
      grant_type: authorization_code
